### ISSUE TITLE
Limite ?

### ISSUE THREAD

**Issue by richardvidal** [sgmap/api-avis-imposition#13]
Bonjour, est-ce que l'on sait si il y a une limite du nombre de demandes pouvant être effectuées sur svair par adresse IP?
Je vous remercie.

**Comment by Bernardstanislas** [comment]
Bonjour,

Il n'y a pas de limite de demandes, il y a en revanche une limite concernant le nombre de demandes **en échec** (identifiants introuvables/invalides).

Je ne connais pas cette limite de manière quantitative.

Désolé du délai de réponse je n'avais pas vu votre question...
